---
- name: NTP Installation
  hosts: node1
  become: yes
  become_method: sudo
  roles:
    - role: geerlingguy.ntp
      ntp_manage_config: true
      ntp_servers:
        - 0.fr.pool.ntp.org
        - 1.fr.pool.ntp.org
        - 2.fr.pool.ntp.org
        - 3.fr.pool.ntp.org
      ntp_timezone: Europe/Paris
