---
- name: NTP Installation
  hosts: all
  become: yes
  vars:
    ip_local_ntp_server: "100.74.37.243"
  become_method: sudo
  roles:
    - role: geerlingguy.ntp
      ntp_manage_config: true
      ntp_servers: 
        - "{{ip_local_ntp_server}}"
      ntp_timezone: Europe/Paris
      ntp_restrict:
        - "127.0.0.1"
        - "::1"
